//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeAppWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleInput
    {
        public int ID { get; set; }
        public Nullable<int> ID_Staff { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
