//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeAppWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trash
    {
        public int ID { get; set; }
        public int ID_User { get; set; }
        public int ID_Flower { get; set; }
        public int Count { get; set; }
    
        public virtual Flower Flower { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
